Version 3.6.6: Allow configuration items to have a value of empty string and update to alpine base container 3.15.4

diff --git a/runit_bootstrap b/runit_bootstrap
--- a/runit_bootstrap
+++ b/runit_bootstrap
@@ -16,8 +16,8 @@ add_config_value() {
   key=${1}
   value=${2}
   config_file=${3:-/etc/postfix/main.cf}
-  [ "${key}" = "" ] && echo "ERROR: No key set !!" && exit 1
-  [ "${value}" = "" ] && echo "ERROR: No value set !!" && exit 1
+  [ "${key}" = "" ] && echo "ERROR: No key set!" && exit 1
+  [ "${value}" = "" ] && echo "WARNING: No value set for key ${key}!"
   property_hits=$(grep -v '^#' "$config_file" | grep -c $key)
   if [ $property_hits -eq 0 ]
   then
